spring:
  application:
    name: userservice
  datasource:
    url: jdbc:mysql://localhost:3306/employee_db
    username: root
    password: pass123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
server:
  port: 8001